// <auto-generated />
using System;
using LibraryManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260904133812_AddSeedingData")]
    partial class AddSeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagementSystem.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Robert C. Martin",
                            CategoryId = 1,
                            Price = 45.0,
                            PublishedYear = 2017,
                            Title = "Clean Architecture"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Jon Skeet",
                            CategoryId = 1,
                            Price = 49.990000000000002,
                            PublishedYear = 2019,
                            Title = "C# in Depth"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Eric Evans",
                            CategoryId = 1,
                            Price = 55.0,
                            PublishedYear = 2003,
                            Title = "Domain-Driven Design"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Robert C. Martin",
                            CategoryId = 1,
                            Price = 40.0,
                            PublishedYear = 2008,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Adam Freeman",
                            CategoryId = 1,
                            Price = 52.0,
                            PublishedYear = 2022,
                            Title = "Pro ASP.NET Core"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Martin Kleppmann",
                            CategoryId = 2,
                            Price = 39.990000000000002,
                            PublishedYear = 2017,
                            Title = "Designing Data-Intensive Applications"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Itzik Ben-Gan",
                            CategoryId = 2,
                            Price = 35.0,
                            PublishedYear = 2016,
                            Title = "T-SQL Fundamentals"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Jon Smith",
                            CategoryId = 2,
                            Price = 42.0,
                            PublishedYear = 2021,
                            Title = "Entity Framework Core in Action"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Regina O. Obe",
                            CategoryId = 2,
                            Price = 38.0,
                            PublishedYear = 2017,
                            Title = "PostgreSQL: Up and Running"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Abraham Silberschatz",
                            CategoryId = 2,
                            Price = 85.0,
                            PublishedYear = 2019,
                            Title = "Database System Concepts"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Thomas H. Cormen",
                            CategoryId = 3,
                            Price = 95.0,
                            PublishedYear = 2009,
                            Title = "Introduction to Algorithms"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Aditya Bhargava",
                            CategoryId = 3,
                            Price = 34.0,
                            PublishedYear = 2016,
                            Title = "Grokking Algorithms"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Steve McConnell",
                            CategoryId = 3,
                            Price = 45.0,
                            PublishedYear = 2004,
                            Title = "Code Complete"
                        },
                        new
                        {
                            Id = 14,
                            Author = "David Thomas",
                            CategoryId = 3,
                            Price = 40.0,
                            PublishedYear = 2019,
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Martin Fowler",
                            CategoryId = 3,
                            Price = 48.0,
                            PublishedYear = 2018,
                            Title = "Refactoring"
                        },
                        new
                        {
                            Id = 16,
                            Author = "David Harris",
                            CategoryId = 4,
                            Price = 75.0,
                            PublishedYear = 2012,
                            Title = "Digital Design and Computer Architecture"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Mark Siegesmund",
                            CategoryId = 4,
                            Price = 55.0,
                            PublishedYear = 2014,
                            Title = "Embedded C Programming"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Dogan Ibrahim",
                            CategoryId = 4,
                            Price = 45.0,
                            PublishedYear = 2020,
                            Title = "STM32 Microcontroller Programming"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Kenneth L. Short",
                            CategoryId = 4,
                            Price = 65.0,
                            PublishedYear = 2008,
                            Title = "VHDL for Engineers"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Robert Britton",
                            CategoryId = 4,
                            Price = 35.0,
                            PublishedYear = 2003,
                            Title = "MIPS Assembly Language Programming"
                        },
                        new
                        {
                            Id = 21,
                            Author = "Nigel Poulton",
                            CategoryId = 5,
                            Price = 30.0,
                            PublishedYear = 2020,
                            Title = "Docker Deep Dive"
                        },
                        new
                        {
                            Id = 22,
                            Author = "Brendan Burns",
                            CategoryId = 5,
                            Price = 42.0,
                            PublishedYear = 2019,
                            Title = "Kubernetes Up & Running"
                        },
                        new
                        {
                            Id = 23,
                            Author = "Gene Kim",
                            CategoryId = 5,
                            Price = 25.0,
                            PublishedYear = 2013,
                            Title = "The Phoenix Project"
                        },
                        new
                        {
                            Id = 24,
                            Author = "Jez Humble",
                            CategoryId = 5,
                            Price = 45.0,
                            PublishedYear = 2010,
                            Title = "Continuous Delivery"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Cornelia Davis",
                            CategoryId = 5,
                            Price = 40.0,
                            PublishedYear = 2019,
                            Title = "Cloud Native Patterns"
                        },
                        new
                        {
                            Id = 26,
                            Author = "Shyam Seshadri",
                            CategoryId = 6,
                            Price = 38.0,
                            PublishedYear = 2018,
                            Title = "Angular Up and Running"
                        },
                        new
                        {
                            Id = 27,
                            Author = "Toi B. Wright",
                            CategoryId = 6,
                            Price = 44.0,
                            PublishedYear = 2021,
                            Title = "Blazor WebAssembly by Example"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Douglas Crockford",
                            CategoryId = 6,
                            Price = 29.0,
                            PublishedYear = 2008,
                            Title = "JavaScript: The Good Parts"
                        },
                        new
                        {
                            Id = 29,
                            Author = "Brian Hogan",
                            CategoryId = 6,
                            Price = 32.0,
                            PublishedYear = 2013,
                            Title = "HTML5 and CSS3"
                        },
                        new
                        {
                            Id = 30,
                            Author = "Josh Goldberg",
                            CategoryId = 6,
                            Price = 39.0,
                            PublishedYear = 2022,
                            Title = "Learning TypeScript"
                        },
                        new
                        {
                            Id = 31,
                            Author = "Frank Herbert",
                            CategoryId = 7,
                            Price = 15.99,
                            PublishedYear = 1965,
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 32,
                            Author = "Isaac Asimov",
                            CategoryId = 7,
                            Price = 14.99,
                            PublishedYear = 1951,
                            Title = "Foundation"
                        },
                        new
                        {
                            Id = 33,
                            Author = "William Gibson",
                            CategoryId = 7,
                            Price = 16.0,
                            PublishedYear = 1984,
                            Title = "Neuromancer"
                        },
                        new
                        {
                            Id = 34,
                            Author = "Neal Stephenson",
                            CategoryId = 7,
                            Price = 17.5,
                            PublishedYear = 1992,
                            Title = "Snow Crash"
                        },
                        new
                        {
                            Id = 35,
                            Author = "Andy Weir",
                            CategoryId = 7,
                            Price = 18.0,
                            PublishedYear = 2014,
                            Title = "The Martian"
                        },
                        new
                        {
                            Id = 36,
                            Author = "George Orwell",
                            CategoryId = 8,
                            Price = 12.0,
                            PublishedYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 37,
                            Author = "Harper Lee",
                            CategoryId = 8,
                            Price = 14.0,
                            PublishedYear = 1960,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 38,
                            Author = "Jane Austen",
                            CategoryId = 8,
                            Price = 10.0,
                            PublishedYear = 1813,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 39,
                            Author = "F. Scott Fitzgerald",
                            CategoryId = 8,
                            Price = 11.5,
                            PublishedYear = 1925,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 40,
                            Author = "Herman Melville",
                            CategoryId = 8,
                            Price = 15.0,
                            PublishedYear = 1851,
                            Title = "Moby Dick"
                        },
                        new
                        {
                            Id = 41,
                            Author = "Yuval Noah Harari",
                            CategoryId = 9,
                            Price = 22.0,
                            PublishedYear = 2011,
                            Title = "Sapiens"
                        },
                        new
                        {
                            Id = 42,
                            Author = "Jared Diamond",
                            CategoryId = 9,
                            Price = 20.0,
                            PublishedYear = 1997,
                            Title = "Guns, Germs, and Steel"
                        },
                        new
                        {
                            Id = 43,
                            Author = "Howard Zinn",
                            CategoryId = 9,
                            Price = 19.5,
                            PublishedYear = 1980,
                            Title = "A People's History"
                        },
                        new
                        {
                            Id = 44,
                            Author = "Peter Frankopan",
                            CategoryId = 9,
                            Price = 24.0,
                            PublishedYear = 2015,
                            Title = "The Silk Roads"
                        },
                        new
                        {
                            Id = 45,
                            Author = "Mary Beard",
                            CategoryId = 9,
                            Price = 21.0,
                            PublishedYear = 2015,
                            Title = "SPQR: A History of Ancient Rome"
                        },
                        new
                        {
                            Id = 46,
                            Author = "Daniel Kahneman",
                            CategoryId = 10,
                            Price = 18.0,
                            PublishedYear = 2011,
                            Title = "Thinking, Fast and Slow"
                        },
                        new
                        {
                            Id = 47,
                            Author = "James Clear",
                            CategoryId = 10,
                            Price = 20.0,
                            PublishedYear = 2018,
                            Title = "Atomic Habits"
                        },
                        new
                        {
                            Id = 48,
                            Author = "Jim Collins",
                            CategoryId = 10,
                            Price = 22.0,
                            PublishedYear = 2001,
                            Title = "Good to Great"
                        },
                        new
                        {
                            Id = 49,
                            Author = "Eric Ries",
                            CategoryId = 10,
                            Price = 19.0,
                            PublishedYear = 2011,
                            Title = "The Lean Startup"
                        },
                        new
                        {
                            Id = 50,
                            Author = "Peter Thiel",
                            CategoryId = 10,
                            Price = 17.5,
                            PublishedYear = 2014,
                            Title = "Zero to One"
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.Entities.Borrowing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("MemberId", "BookId");

                    b.ToTable("Borrowings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            BorrowDate = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 1,
                            ReturnDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            BorrowDate = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 1,
                            ReturnDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BookId = 3,
                            BorrowDate = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 2,
                            ReturnDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            BookId = 8,
                            BorrowDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 2,
                            ReturnDate = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            BookId = 1,
                            BorrowDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 3,
                            ReturnDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            BookId = 11,
                            BorrowDate = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 3,
                            ReturnDate = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            BookId = 4,
                            BorrowDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 4,
                            ReturnDate = new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            BookId = 5,
                            BorrowDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 5,
                            ReturnDate = new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            BookId = 2,
                            BorrowDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 6,
                            ReturnDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            BookId = 6,
                            BorrowDate = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 7,
                            ReturnDate = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            BookId = 10,
                            BorrowDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 8,
                            ReturnDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            BookId = 12,
                            BorrowDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 9,
                            ReturnDate = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            BookId = 13,
                            BorrowDate = new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 10,
                            ReturnDate = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            BookId = 14,
                            BorrowDate = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 11,
                            ReturnDate = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            BookId = 15,
                            BorrowDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 12,
                            ReturnDate = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            BookId = 1,
                            BorrowDate = new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 13,
                            ReturnDate = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            BookId = 23,
                            BorrowDate = new DateTime(2026, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 14,
                            ReturnDate = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            BookId = 24,
                            BorrowDate = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 15,
                            ReturnDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            BookId = 25,
                            BorrowDate = new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 16,
                            ReturnDate = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            BookId = 28,
                            BorrowDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 17,
                            ReturnDate = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            BookId = 29,
                            BorrowDate = new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 18,
                            ReturnDate = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            BookId = 30,
                            BorrowDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 19,
                            ReturnDate = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            BookId = 33,
                            BorrowDate = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 20,
                            ReturnDate = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            BookId = 7,
                            BorrowDate = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 4,
                            ReturnDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            BookId = 26,
                            BorrowDate = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 4,
                            ReturnDate = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            BookId = 27,
                            BorrowDate = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 5,
                            ReturnDate = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            BookId = 17,
                            BorrowDate = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 6,
                            ReturnDate = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            BookId = 19,
                            BorrowDate = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 8,
                            ReturnDate = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            BookId = 31,
                            BorrowDate = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 10,
                            ReturnDate = new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            BookId = 43,
                            BorrowDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 3,
                            ReturnDate = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            BookId = 21,
                            BorrowDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 2,
                            ReturnDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            BookId = 18,
                            BorrowDate = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 7,
                            ReturnDate = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            BookId = 20,
                            BorrowDate = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 9,
                            ReturnDate = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            BookId = 36,
                            BorrowDate = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 11,
                            ReturnDate = new DateTime(2026, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            BookId = 41,
                            BorrowDate = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 12,
                            ReturnDate = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            BookId = 22,
                            BorrowDate = new DateTime(2026, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 13,
                            ReturnDate = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            BookId = 46,
                            BorrowDate = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 14,
                            ReturnDate = new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            BookId = 32,
                            BorrowDate = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 15,
                            ReturnDate = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            BookId = 47,
                            BorrowDate = new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 16,
                            ReturnDate = new DateTime(2026, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            BookId = 37,
                            BorrowDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 17,
                            ReturnDate = new DateTime(2026, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            BookId = 42,
                            BorrowDate = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 18,
                            ReturnDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 42,
                            BookId = 48,
                            BorrowDate = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 19,
                            ReturnDate = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            BookId = 49,
                            BorrowDate = new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 20,
                            ReturnDate = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 44,
                            BookId = 34,
                            BorrowDate = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 1,
                            ReturnDate = new DateTime(2026, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 45,
                            BookId = 38,
                            BorrowDate = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 2,
                            ReturnDate = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 46,
                            BookId = 50,
                            BorrowDate = new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 4,
                            ReturnDate = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 47,
                            BookId = 35,
                            BorrowDate = new DateTime(2026, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 5,
                            ReturnDate = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 48,
                            BookId = 39,
                            BorrowDate = new DateTime(2026, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 6,
                            ReturnDate = new DateTime(2026, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 49,
                            BookId = 44,
                            BorrowDate = new DateTime(2026, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 7,
                            ReturnDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 50,
                            BookId = 1,
                            BorrowDate = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 8,
                            ReturnDate = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 51,
                            BookId = 2,
                            BorrowDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 9,
                            ReturnDate = new DateTime(2026, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 52,
                            BookId = 3,
                            BorrowDate = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 10,
                            ReturnDate = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 53,
                            BookId = 4,
                            BorrowDate = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 11,
                            ReturnDate = new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 54,
                            BookId = 5,
                            BorrowDate = new DateTime(2026, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 12,
                            ReturnDate = new DateTime(2026, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 55,
                            BookId = 6,
                            BorrowDate = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 13,
                            ReturnDate = new DateTime(2026, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 56,
                            BookId = 7,
                            BorrowDate = new DateTime(2026, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 14,
                            ReturnDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 57,
                            BookId = 8,
                            BorrowDate = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 15,
                            ReturnDate = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 58,
                            BookId = 9,
                            BorrowDate = new DateTime(2026, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 16,
                            ReturnDate = new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 59,
                            BookId = 10,
                            BorrowDate = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 17,
                            ReturnDate = new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 60,
                            BookId = 11,
                            BorrowDate = new DateTime(2026, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 18,
                            ReturnDate = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 61,
                            BookId = 12,
                            BorrowDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 19,
                            ReturnDate = new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 62,
                            BookId = 13,
                            BorrowDate = new DateTime(2026, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 20,
                            ReturnDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 63,
                            BookId = 14,
                            BorrowDate = new DateTime(2026, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 1,
                            ReturnDate = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 64,
                            BookId = 15,
                            BorrowDate = new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 2,
                            ReturnDate = new DateTime(2026, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 65,
                            BookId = 16,
                            BorrowDate = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 3,
                            ReturnDate = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 66,
                            BookId = 17,
                            BorrowDate = new DateTime(2026, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 4,
                            ReturnDate = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 67,
                            BookId = 18,
                            BorrowDate = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 5,
                            ReturnDate = new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 68,
                            BookId = 19,
                            BorrowDate = new DateTime(2026, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 6,
                            ReturnDate = new DateTime(2026, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 69,
                            BookId = 20,
                            BorrowDate = new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 7,
                            ReturnDate = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 70,
                            BookId = 21,
                            BorrowDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 8,
                            ReturnDate = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 71,
                            BookId = 22,
                            BorrowDate = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 9,
                            ReturnDate = new DateTime(2026, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 72,
                            BookId = 23,
                            BorrowDate = new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 10,
                            ReturnDate = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 73,
                            BookId = 24,
                            BorrowDate = new DateTime(2026, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 11,
                            ReturnDate = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 74,
                            BookId = 25,
                            BorrowDate = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 12,
                            ReturnDate = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 75,
                            BookId = 26,
                            BorrowDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 13,
                            ReturnDate = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 76,
                            BookId = 27,
                            BorrowDate = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 14,
                            ReturnDate = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 77,
                            BookId = 28,
                            BorrowDate = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 15,
                            ReturnDate = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 78,
                            BookId = 29,
                            BorrowDate = new DateTime(2026, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 16,
                            ReturnDate = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 79,
                            BookId = 30,
                            BorrowDate = new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 17,
                            ReturnDate = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 80,
                            BookId = 31,
                            BorrowDate = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 18,
                            ReturnDate = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 81,
                            BookId = 32,
                            BorrowDate = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 19
                        },
                        new
                        {
                            Id = 82,
                            BookId = 33,
                            BorrowDate = new DateTime(2026, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 20
                        },
                        new
                        {
                            Id = 83,
                            BookId = 34,
                            BorrowDate = new DateTime(2026, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 1
                        },
                        new
                        {
                            Id = 84,
                            BookId = 35,
                            BorrowDate = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 2
                        },
                        new
                        {
                            Id = 85,
                            BookId = 36,
                            BorrowDate = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 3
                        },
                        new
                        {
                            Id = 86,
                            BookId = 37,
                            BorrowDate = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 4
                        },
                        new
                        {
                            Id = 87,
                            BookId = 38,
                            BorrowDate = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 5
                        },
                        new
                        {
                            Id = 88,
                            BookId = 39,
                            BorrowDate = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 6
                        },
                        new
                        {
                            Id = 89,
                            BookId = 40,
                            BorrowDate = new DateTime(2026, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 7
                        },
                        new
                        {
                            Id = 90,
                            BookId = 41,
                            BorrowDate = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 8
                        },
                        new
                        {
                            Id = 91,
                            BookId = 42,
                            BorrowDate = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 9
                        },
                        new
                        {
                            Id = 92,
                            BookId = 43,
                            BorrowDate = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 10
                        },
                        new
                        {
                            Id = 93,
                            BookId = 44,
                            BorrowDate = new DateTime(2026, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 11
                        },
                        new
                        {
                            Id = 94,
                            BookId = 45,
                            BorrowDate = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 12
                        },
                        new
                        {
                            Id = 95,
                            BookId = 46,
                            BorrowDate = new DateTime(2026, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 13
                        },
                        new
                        {
                            Id = 96,
                            BookId = 47,
                            BorrowDate = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 14
                        },
                        new
                        {
                            Id = 97,
                            BookId = 48,
                            BorrowDate = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 15
                        },
                        new
                        {
                            Id = 98,
                            BookId = 49,
                            BorrowDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 16
                        },
                        new
                        {
                            Id = 99,
                            BookId = 50,
                            BorrowDate = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 17
                        },
                        new
                        {
                            Id = 100,
                            BookId = 16,
                            BorrowDate = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 1
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Software Engineering"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Database Architecture"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hardware & Embedded Systems"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cloud & DevOps"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Frontend Development"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Classic Literature"
                        },
                        new
                        {
                            Id = 9,
                            Name = "History"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Business & Productivity"
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "omar@example.com",
                            Name = "Omar Gomaa",
                            Phone = "01011112222"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ahmed.e@example.com",
                            Name = "Ahmed Mostafa",
                            Phone = "01022223333"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Ali@example.com",
                            Name = "Ali Omar",
                            Phone = "01033334444"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Malak@example.com",
                            Name = "Malak Khaled",
                            Phone = "01044445555"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Osman@example.com",
                            Name = "Osman Mohammed",
                            Phone = "01055556666"
                        },
                        new
                        {
                            Id = 6,
                            Email = "mohamed.b@example.com",
                            Name = "Mohamed Bakr",
                            Phone = "01066667777"
                        },
                        new
                        {
                            Id = 7,
                            Email = "menna@example.com",
                            Name = "Mennatallah Madian",
                            Phone = "01077778888"
                        },
                        new
                        {
                            Id = 8,
                            Email = "abdoo@example.com",
                            Name = "Abdoo Sherif",
                            Phone = "01088889999"
                        },
                        new
                        {
                            Id = 9,
                            Email = "abdullah@example.com",
                            Name = "Abdullah Saied",
                            Phone = "01099990000"
                        },
                        new
                        {
                            Id = 10,
                            Email = "omar.k@example.com",
                            Name = "Omar Khaled",
                            Phone = "01112223333"
                        },
                        new
                        {
                            Id = 11,
                            Email = "essam@example.com",
                            Name = "Essam Youssef",
                            Phone = "01123334444"
                        },
                        new
                        {
                            Id = 12,
                            Email = "nourhan@example.com",
                            Name = "Nourhan Tarek",
                            Phone = "01134445555"
                        },
                        new
                        {
                            Id = 13,
                            Email = "karim@example.com",
                            Name = "Karim Mostafa",
                            Phone = "01145556666"
                        },
                        new
                        {
                            Id = 14,
                            Email = "hadeer@example.com",
                            Name = "Hadeer Ibrahim",
                            Phone = "01156667777"
                        },
                        new
                        {
                            Id = 15,
                            Email = "mahmoud@example.com",
                            Name = "Mahmoud Fawzy",
                            Phone = "01167778888"
                        },
                        new
                        {
                            Id = 16,
                            Email = "nada@example.com",
                            Name = "Nada Hassan",
                            Phone = "01278889999"
                        },
                        new
                        {
                            Id = 17,
                            Email = "ziad@example.com",
                            Name = "Ziad Kamal",
                            Phone = "01289990000"
                        },
                        new
                        {
                            Id = 18,
                            Email = "farah@example.com",
                            Name = "Farah Nabil",
                            Phone = "01290001111"
                        },
                        new
                        {
                            Id = 19,
                            Email = "youssef@example.com",
                            Name = "Youssef Ahmed",
                            Phone = "01511112222"
                        },
                        new
                        {
                            Id = 20,
                            Email = "khaled@example.com",
                            Name = "Khaled Zaki",
                            Phone = "01522223333"
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.Entities.Book", b =>
                {
                    b.HasOne("LibraryManagementSystem.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LibraryManagementSystem.Entities.Borrowing", b =>
                {
                    b.HasOne("LibraryManagementSystem.Entities.Book", "Book")
                        .WithMany("Borrowings")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagementSystem.Entities.Member", "Member")
                        .WithMany("Borrowings")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LibraryManagementSystem.Entities.Book", b =>
                {
                    b.Navigation("Borrowings");
                });

            modelBuilder.Entity("LibraryManagementSystem.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryManagementSystem.Entities.Member", b =>
                {
                    b.Navigation("Borrowings");
                });
#pragma warning restore 612, 618
        }
    }
}
